### PR TITLE
Create image lists doc

### LINKED ISSUE #69302: Add official support for material design image lists types
MD docs available at: https://material.io/components/image-lists

## Use case

The masonry image list is useful to achieve Google Keep UI style, the quilted image list could be cool for something like a news app and woven image list is already used on the Shrine material study

## Proposal

I would add some sliver delegates to use with the gridDelegate GridView param, to keep compatibility with older gridview and also provide an easy to use api. For example for the woven image list offer an aspect ratio param, for the quilted image list you could use another widget like "GridTile.quilted(crossAxisExtent: ...)" and for the masonry grid just shrinkwrap vertically tiles. It would be nice to also add support for reorder/animations

### PR DESCRIPTION
**Pull request by guidezpl**
For https://material.io/components/image-lists/flutter

### Related issues
Closes https://github.com/flutter/flutter/issues/69302

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM

**Comment by McClernan** [comment]
## DESIGN tab

[https://material.io/components/image-lists#anatomy
](https://material.io/components/image-lists#anatomy
)
### Padding
Better to say "among" than "between" 
"Padding can vary **among** images in an image list"
_(rather than ""Padding can vary **between** images in an image list")_

<hr>

[https://material.io/components/image-lists#behavior
](https://material.io/components/image-lists#behavior
)
### Actions

Better to say:
Image **list** items may be tapped, dragged, filtered, or sorted.
_(list rather than lists)_

Better to say:
Tapping an image list item displays **details** about that item.
_(rather than: Tapping an image list item displays more detail about that item.)_

#### Reflow

Better to say:
When a container increases in size, **its content** should also increase,
_(rather than: When a container increases in size, the content inside of it should also increase,)_

### Scaling and Adaptation
Better to say:
**An** example of **a** list of items
_(rather than "Example of list of items")_
<hr>

[https://material.io/components/image-lists#types
](https://material.io/components/image-lists#types
)

### Quilted image list
Better to say:
"to create an image hierarchy"
 _(rather than: "to create hierarchy across images.)_

### 


## IMPLEMENTATION tab
No Flutter implementation guidance available

**Comment by letsar** [comment]
Thanks for this PR @guidezpl! However it seems that the https://material.io/components/image-lists/flutter web page has not been updated. Is there something to do to update it from the GitHub repo?

**Comment by guidezpl** [comment]
I filed an internal bug (b/218299197) to get that page updated, thanks Romain.

**Pull request merged**
